"""金融投研 Prompt 模板体系。"""

from .finance_planner import (
    INTENT_ANALYSIS_PROMPT,
    ENTITY_EXTRACTION_PROMPT,
    TASK_PLANNING_PROMPT,
)
from .finance_report import (
    REPORT_SYSTEM_PROMPT,
    SECTION_GENERATION_PROMPT,
    SOURCE_ANNOTATION_PROMPT,
)
from .compliance import (
    DISCLAIMER_TEMPLATES,
    AI_MARKER,
    FORBIDDEN_PATTERNS,
    MANDATORY_CHECKLIST,
)

__all__ = [
    "INTENT_ANALYSIS_PROMPT",
    "ENTITY_EXTRACTION_PROMPT",
    "TASK_PLANNING_PROMPT",
    "REPORT_SYSTEM_PROMPT",
    "SECTION_GENERATION_PROMPT",
    "SOURCE_ANNOTATION_PROMPT",
    "DISCLAIMER_TEMPLATES",
    "AI_MARKER",
    "FORBIDDEN_PATTERNS",
    "MANDATORY_CHECKLIST",
]
